CREATE TABLE 'ENROLEES' (
	'ENROLE_ID'	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'FIRST_NAME'	TEXT NOT NULL,
	'MIDDLE_NAME'   TEXT NOT NULL,
	'LAST_NAME'     TEXT NOT NULL,
	'ADDRESS'       TEXT
);